# Generated by Django 3.2.13 on 2022-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='car_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Araç Fotoğrafı Yükleyiniz.'),
        ),
    ]
