# Generated by Django 3.2.13 on 2022-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_plate_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
